# Generated by Django 5.2 on 2025-05-31 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_compra_produtos_itemcompra_compra_itens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='itens',
            new_name='produtos',
        ),
    ]
