# Generated by Django 5.2 on 2025-05-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_itens_compra_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='valor_total_dos_produtos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
